FROM node:13-alpine3.11 AS installer

RUN mkdir /app
WORKDIR /app

COPY package*.json /app/

RUN npm install

FROM node:13-alpine3.11

RUN mkdir /app
WORKDIR /app

COPY server.js /app

COPY --from=installer /app/package.json .
COPY --from=installer /app/node_modules ./node_modules

EXPOSE 3000

CMD ["node", "server.js"]
