apiVersion: v1
kind: Service
metadata:
  labels:
    app: mkingst-node-app
  name: node-service
  namespace: default
spec:
  ports:
  - name: service
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: mkingst-node-app
  type: ClusterIP
