apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-app-monitor
  labels:
    release: monitoring
    app: mkingst-node-app
spec:
  selector:
    matchLabels:
      app: mkingst-node-app
  namespaceSelector:
    matchNames: 
    - default
  endpoints:
    - path: /metrics
      port: service
      targetPort: 3000
